version: '3.8'

services:
  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: ./src/services/user-service/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - rabbitmq
    environment:
      PORT: 3001
      DATABASE_URL: 'mongodb://mongo:27017/users_db'
      RABBIT_MQ_URL: 'amqp://rabbitmq:5672'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://user-service:3001/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

  notification-service:
    container_name: notification-service
    build:
      context: .
      dockerfile: ./src/services/notification-service/Dockerfile
    ports:
      - 3002:3002
    depends_on:
      - rabbitmq
    environment:
      NOTIFICATION_SERVICE_PORT: 3002
      RABBIT_MQ_URL: 'amqp://rabbitmq:5672'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://notification-service:3002/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: users_db

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbit-mq
    ports:
      - 5672:5672
      - 15672:15672
